version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - server

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/api
      - REDIS_URL=redis://redis:6379  

  
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mongodb_data: